# Simple workflow for deploying static content to GitHub Pages
name: Build

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Compile sources
        run: npm run build
